# Generated by Django 5.1.6 on 2025-02-26 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('naics', models.IntegerField()),
                ('new_exist', models.IntegerField()),
                ('retained_job', models.IntegerField()),
                ('franchise_code', models.IntegerField()),
                ('urban_rural', models.IntegerField()),
                ('gr_appv', models.FloatField()),
                ('bank', models.CharField(max_length=255)),
                ('term', models.IntegerField()),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
