# Generated by Django 5.1.6 on 2025-02-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='advisor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ai_approved', 'Approuvé par IA'), ('ai_rejected', 'Rejeté par IA'), ('advisor_approved', 'Approuvé par conseiller'), ('advisor_rejected', 'Rejeté par conseiller')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
